version: '3.8'

services:
  kanban-web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://kanban-api.tantai.dev
      - NEXT_PUBLIC_APP_URL=https://kanban.tantai.dev
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - kanban-network

networks:
  kanban-network:
    driver: bridge 