#!/bin/bash

echo "🔌 WebSocket Testing Options:"
echo ""
echo "1. Test with local API server (recommended)"
echo "   - Start your local API server first"
echo "   - Then run: npm run dev"
echo ""
echo "2. Test with production WebSocket only"
echo "   - Edit lib/websocket.ts to force production URL"
echo "   - Comment out the development check"
echo ""
echo "3. Test with both local and production fallback"
echo "   - Current setup: tries local first, falls back to production"
echo ""
echo "4. Disable WebSocket completely for development"
echo "   - Edit lib/websocket.ts to skip connection in development"
echo ""
echo "Current setup:"
echo "- Development mode: tries ws://localhost:8080 first"
echo "- If local fails: falls back to wss://kanban-api.ngtantai.pro"
echo "- Production mode: uses wss://kanban-api.ngtantai.pro directly"
echo ""
echo "To start local API server (if you have it):"
echo "cd ../kanban-api && go run main.go"
echo ""
echo "To test current setup:"
echo "npm run dev" 